### ISSUE TITLE
Further improvements

### ISSUE THREAD

**Issue by superware** [haestflod/asp.net-mvc-core-1.0-localized-routing#1]
"I am going to try a different approach in a few weeks with my new knowledge about routing in asp.net", can you please elaborate?

Thanks!

**Comment by haestflod** [comment]
It was to extend IRouter and it failed. 

Here's the full answer: 
http://haestflod.blogspot.se/2016/01/localized-routing-aspnet-5-mvc-6.html?showComment=1469787989676#c7798259948680540453
